//go:build !ignore_autogenerated

/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/api/resource/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindRequest) DeepCopyInto(out *BindRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindRequest.
func (in *BindRequest) DeepCopy() *BindRequest {
	if in == nil {
		return nil
	}
	out := new(BindRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BindRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindRequestList) DeepCopyInto(out *BindRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BindRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindRequestList.
func (in *BindRequestList) DeepCopy() *BindRequestList {
	if in == nil {
		return nil
	}
	out := new(BindRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BindRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindRequestSpec) DeepCopyInto(out *BindRequestSpec) {
	*out = *in
	if in.ReceivedGPU != nil {
		in, out := &in.ReceivedGPU, &out.ReceivedGPU
		*out = new(ReceivedGPU)
		**out = **in
	}
	if in.SelectedGPUGroups != nil {
		in, out := &in.SelectedGPUGroups, &out.SelectedGPUGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SelectedFractionalGpuGroups != nil {
		in, out := &in.SelectedFractionalGpuGroups, &out.SelectedFractionalGpuGroups
		*out = make([]FractionalGpuGroup, len(*in))
		copy(*out, *in)
	}
	if in.ResourceClaimAllocations != nil {
		in, out := &in.ResourceClaimAllocations, &out.ResourceClaimAllocations
		*out = make([]ResourceClaimAllocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtendedResourceClaimAllocation != nil {
		in, out := &in.ExtendedResourceClaimAllocation, &out.ExtendedResourceClaimAllocation
		*out = new(ExtendedResourceClaimAllocation)
		(*in).DeepCopyInto(*out)
	}
	if in.PredictedNUMAZones != nil {
		in, out := &in.PredictedNUMAZones, &out.PredictedNUMAZones
		*out = make([]NUMAZonePlacement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PredictedNUMAMemoryGroups != nil {
		in, out := &in.PredictedNUMAMemoryGroups, &out.PredictedNUMAMemoryGroups
		*out = make([]NUMAMemoryGroupPlacement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindRequestSpec.
func (in *BindRequestSpec) DeepCopy() *BindRequestSpec {
	if in == nil {
		return nil
	}
	out := new(BindRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindRequestStatus) DeepCopyInto(out *BindRequestStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindRequestStatus.
func (in *BindRequestStatus) DeepCopy() *BindRequestStatus {
	if in == nil {
		return nil
	}
	out := new(BindRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtendedResourceClaimAllocation) DeepCopyInto(out *ExtendedResourceClaimAllocation) {
	*out = *in
	if in.Allocation != nil {
		in, out := &in.Allocation, &out.Allocation
		*out = new(v1.AllocationResult)
		(*in).DeepCopyInto(*out)
	}
	if in.DeviceRequests != nil {
		in, out := &in.DeviceRequests, &out.DeviceRequests
		*out = make([]v1.DeviceRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContainerMappings != nil {
		in, out := &in.ContainerMappings, &out.ContainerMappings
		*out = make([]corev1.ContainerExtendedResourceRequest, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtendedResourceClaimAllocation.
func (in *ExtendedResourceClaimAllocation) DeepCopy() *ExtendedResourceClaimAllocation {
	if in == nil {
		return nil
	}
	out := new(ExtendedResourceClaimAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FractionalGpuGroup) DeepCopyInto(out *FractionalGpuGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FractionalGpuGroup.
func (in *FractionalGpuGroup) DeepCopy() *FractionalGpuGroup {
	if in == nil {
		return nil
	}
	out := new(FractionalGpuGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUMAMemoryGroupPlacement) DeepCopyInto(out *NUMAMemoryGroupPlacement) {
	*out = *in
	if in.MemoryNodes != nil {
		in, out := &in.MemoryNodes, &out.MemoryNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUMAMemoryGroupPlacement.
func (in *NUMAMemoryGroupPlacement) DeepCopy() *NUMAMemoryGroupPlacement {
	if in == nil {
		return nil
	}
	out := new(NUMAMemoryGroupPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUMAZonePlacement) DeepCopyInto(out *NUMAZonePlacement) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUMAZonePlacement.
func (in *NUMAZonePlacement) DeepCopy() *NUMAZonePlacement {
	if in == nil {
		return nil
	}
	out := new(NUMAZonePlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceivedGPU) DeepCopyInto(out *ReceivedGPU) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceivedGPU.
func (in *ReceivedGPU) DeepCopy() *ReceivedGPU {
	if in == nil {
		return nil
	}
	out := new(ReceivedGPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceClaimAllocation) DeepCopyInto(out *ResourceClaimAllocation) {
	*out = *in
	if in.Allocation != nil {
		in, out := &in.Allocation, &out.Allocation
		*out = new(v1.AllocationResult)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceClaimAllocation.
func (in *ResourceClaimAllocation) DeepCopy() *ResourceClaimAllocation {
	if in == nil {
		return nil
	}
	out := new(ResourceClaimAllocation)
	in.DeepCopyInto(out)
	return out
}
